version: '3.8'

services:

  api-gw:
    container_name: api-gw-1
    image: api-gw
    build:
      context: ./api-gw
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal
      SERVER_ADDRESS: 0.0.0.0

  food-service-1:
    container_name: food-service-1
    image: food-service
    build:
      context: ./food-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      DB_HOST: host.docker.internal
      SERVER_ADDRESS: 0.0.0.0

  food-service-2:
    container_name: food-service-2
    image: food-service
    ports:
      - "8082:8080"
    environment:
      DB_HOST: host.docker.internal
      SERVER_ADDRESS: 0.0.0.0