version: '3.8'

services:
  api-gw-1:
    container_name: api-gw-1
    build:
      context: ./api-gw
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  food-service-1:
    container_name: food-service-1
    build:
      context: ./food-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"