version: '3.8'

services:

  api-gateway:
    container_name: api-gateway-1
    image: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal
      SERVER_ADDRESS: 0.0.0.0

  payment-service:
    container_name: payment-service-1
    image: payment-service
    build:
      context: payment-service
      dockerfile: Dockerfile
    ports:
      - "8011:8080"
    environment:
      DB_HOST: host.docker.internal
      SERVER_ADDRESS: 0.0.0.0

  shopping-service-1:
    container_name: shopping-service-1
    image: shopping-service
    build:
      context: shopping-service
      dockerfile: Dockerfile
    ports:
      - "8021:8080"
    environment:
      DB_HOST: host.docker.internal
      SERVER_ADDRESS: 0.0.0.0