### test get foods
POST http://{{host}}:8080/food/get-foods
Content-Type: application/json

{
    "foodCategoryIds": [2]
}

### test get foods querydsl
POST http://{{host}}:8080/food/get-foods-querydsl
Content-Type: application/json

{
  "foodCategoryIds": [2]
}

### test get food food categories
GET http://{{host}}:8020/food/get-food-categories-for-food/4
