server:
  port: 8080
spring:
  application:
    name: api-gw
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    version: 2.0
  api-docs:
    path: /api-docs
    version: OPENAPI_3_0
