server:
  port: 8081
spring:
  application:
    name: food-service
  datasource:
    url: jdbc:postgresql://postgres:5432/db_postgres_1
    username:
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    version: 2.0
  api-docs:
    path: /api-docs
    version: OPENAPI_3_0
